docs/index.md, requirements.txt, setup.py, up42/utils.py, up42/workflow.py
- Adjust setup.py
- Small fixes
=> Prepare beta release

docs/03_catalog.md, examples/03_catalog.ipynb, up42/auth.py, up42/catalog.py, up42/tools.py
Remove sobloo from download_quicklooks as not yet implemented.
=> Fix download quicklooks

README.md, docs/authentication.md, docs/support-faq.md, mkdocs.yml
- Use developer submenu in authentication docs
- Simplify readme
=> Docs use developer section

.circleci/config.yml, Makefile, docs/30-seconds-example.md, docs/installation.md, docs/typical-usage.md
- Some docs improvements
- Removes gh-pages ignore from ci file. ci branch would require own ci file.
- Add circle ci ignore deploy method to makefile
=> Docs tests ignore branch

up42/catalog.py, up42/cli.py
- Simplify accepted sensors&blocks logic for catalog search
- fix sensor name sentinel5p
=> Simplify accepted sensors in catalog search

README.md, docs/30-seconds-example.md, docs/installation.md, requirements.txt, tests/context.py, tests/fixtures.py, tests/test_auth.py, tests/test_tools.py, tests/test_utils.py, up42/__init__.py, up42/auth.py, up42/catalog.py, up42/cli.py, up42/job.py, up42/jobtask.py, up42/tools.py, up42/utils.py, up42/workflow.py
- Makes Jupyter installation optional (removed from req, recommended in docs)
- Simplify Ipython kernel check, now just returns the map object if not run in ipython
- Minor improvements to required imports
=> Dependency & import cleanup

README.md
Line 69 minor spelling fix in up42.authenticate
=> minor spelling fix in up42.authenticate

up42/job.py, up42/jobtask.py
Currently no good way to add basic=True, this helps out a bit.
=> add logging to get_results_json

README.md, docs/30-seconds-example.md, docs/catalog.md, docs/examples/airport-monitoring.md, docs/support-faq.md, docs/typical-usage.md, examples/30-seconds-example.ipynb, examples/airports-parallel.ipynb, examples/catalog.ipynb, examples/typical-usage.ipynb
Checked all example docs & notebooks.
=> Minor docs fixes

mkdocs.yml, requirements-dev.txt
add siteurl to enable publishing
=> Mkdocs siteurl

up42/job.py
- Use centroid of all scenes for map focus
- Make image plotting optional
- Better feature info display
=> map_result improvements

up42/__init__.py
Disables/Enables logging output (can be a lot in the notebooks)
=> add settings for logging

tests/fixtures.py, tests/test_workflow.py, up42/workflow.py
Adds job name option. By default takes workflow_name (as in the console) and adds _py
=> Variable job name

tests/test_job.py, tests/test_jobtask.py, tests/test_utils.py, tests/test_workflow.py, up42/utils.py
Removes filtering of data.json from download_results
=> download_results all files

docs/catalog.md, examples/guides/catalog.ipynb, tests/test_catalog.py, up42/catalog.py
=> Replace paramater with parameter

up42/utils.py
buffer 0 in any_vector_to_fc to avoid self intersections.
=> buffer 0 in any_vector_to_fc to avoid self intersections

tests/fixtures.py, tests/test_jobcollection.py, tests/test_workflow.py, up42/job.py, up42/jobcollection.py, up42/workflow.py
Add run and download in parallel methods. Live tests are added. No mock tests so far. I also added some TODOs for future developments.
=> Add parallel job run functionality

coverage.svg, docs/reference/jobcollection.md, docs/theme_override_home/home.html, mkdocs.yml, tests/context.py, tests/fixtures.py, tests/test_jobcollection.py, tests/test_workflow.py, up42/job.py, up42/jobcollection.py, up42/workflow.py
=> Add parallel jobs

tests/test_project.py, tests/test_workflow.py, up42/jobcollection.py, up42/project.py, up42/tools.py, up42/utils.py, up42/workflow.py
Hides empty plot axis, auto aspect ratio
=> Empty last image in plot

pylintrc, tests/test_catalog.py, up42/__init__.py, up42/auth.py, up42/catalog.py, up42/cli.py, up42/job.py, up42/jobtask.py, up42/project.py, up42/tools.py, up42/utils.py, up42/workflow.py
- Makes handling of catalog search query parameter/sorting clearer with sentinel-1 (no cloudcover)
- Uses fstrings for all logging
- Removes "Optional" types for parameters (supposed to be used for optional returns)
- various small improvements see commit messages
- Removes most todos (some added to Jira)
=> Various small improvements

docs/reference/catalog.md, docs/reference/cli.md, docs/reference/job.md, docs/reference/jobcollection.md, docs/reference/jobtask.md, docs/reference/project.md, docs/reference/tools.md, docs/reference/workflow.md, docs/structure.md, docs/stylesheets/extra.css, mkdocs.yml, up42/workflow.py
- Ignores the init function in the code reference & adds the class description as pure markdown, looks much better.
- Adds jobcollection etc.
- Adds a bit more width to the site.
=> Docs improvements

requirements-dev.txt, tests/fixtures.py, tests/test_auth.py, tests/test_catalog.py, tests/test_cli.py, tests/test_job.py, tests/test_project.py, tests/test_utils.py, tests/test_workflow.py, up42/__init__.py, up42/catalog.py, up42/cli.py, up42/job.py, up42/jobtask.py, up42/tools.py, up42/utils.py, up42/workflow.py
Now that geometry validation error messaging is integrated on data block level, removes buffer 0 application in the SDK to keep geometry handling consistent and not run into edge cases (@marooned20 had such an example today, thanks for your help!). 
We could potentially integrate the same validation messaging right in the Python code, topic is still being discussed.
Also lots of new formatting with updated version of black.
=> Remove buffer 0

docs/privacy-policy.md, docs/theme_override_home/main.html, mkdocs.yml
Adds privacy policy chapter to FAQ & cookie consent popup via Google Tag Manager (GTM) injection. All thanks to @afuh !
=> add cookie consent & privacy policy

coverage.svg, tests/test_catalog.py, up42/catalog.py, up42/utils.py
Remove assertion, fix try except for catalog.py plus adding tests.
=> Remove assertion

docs/README.md, docs/catalog.md, examples/guides/catalog.ipynb, mkdocs.yml
Add Quicklooks mapping jupyter example and update catalog docs
=> Quicklook map docs

docs/privacy-policy.md
Replaces the custom privacy policy with the one suggested by @Arnaud-UP42 from the main page.
=> Use up42 default privacy policy

tests/test_auth.py, up42/auth.py
Removes explicit error handling and passes through error message. 
HTTPError or ValueError as the default error?
=> Error messages up4728

README.md, docs/README.md, docs/examples-intro.md, docs/structure.md, docs/support-faq.md
=> replace github io page links with custom subdomain

coverage.svg, tests/test_cli.py, tests/test_job.py, tests/test_jobcollection.py, tests/test_jobtask.py, tests/test_project.py, tests/test_workflow.py, up42/cli.py, up42/job.py, up42/jobcollection.py, up42/jobtask.py, up42/project.py, up42/utils.py, up42/workflow.py
- Adds `info` property.
- Adds `status` property.
- Adds deprecation warnings to `get_info` & `get_status`
Future:
- Keeping the extra `_info` attribute for now, first need to simplify the mock tests with `requests_mock` so that we can use mocks in the fixture.
- Add all suitable "get" functions as class properties, e.g. "project.settings", "workflow.workflow_tasks" etc. for better usability.
Trying to keep the attributes/property section as clean as possible:
Gotta love mkdocs, linkthrough:
=> Info property up4885

requirements.txt
Umpin geopandas version from 0.7.0
=> unpin geopandas version

coverage.svg, tests/fixtures.py
Using constants as suggested in https://github.com/up42/up42-py/pull/151, forgot to push.
=> Use constants in fixtures

tests/test_tools.py
Assert requests exception instead of valueerror
=> fix validate livetest 

docs/examples-intro.md, mkdocs.yml, up42/catalog.py, up42/viztools.py, up42/workflow.py
- Adds aircraft detection example cc @barrynagel
- Consistent behaviour between map_quicklooks and map_results
- Various small improvements
=> Aircraft detection example

up42/utils.py, up42/viztools.py
- Only display the first 100 quicklooks with map_quicklooks
=> Limit map quicklooks

docs/reference/jobcollection-reference.md, docs/structure.md, tests/test_initialization.py, up42/__init__.py
Simplifies the creation of jobcollections of existing jobs for the user.
=> add initialize_jobcollection

coverage.svg, tests/test_auth.py, tests/test_estimation.py, tests/test_visualization.py, tests/test_workflow.py, up42/auth.py, up42/estimation.py
Update estimation endpoint to new `/projects/{projectId}/estimate/job` that includes job parameter validation.
Items:
* [na] Removed credentials
* [na] Removed argument pointing to staging
* [na] Updated [documentation](sdk.up42.com)
=> Update estimation endpoint up5163

README.md, docs/ordering.md, docs/structure.md, examples/guides/ordering.ipynb, mkdocs.yml
PR 3 will include a usage example and docs improvements if needed.
Items:
=> Add ordering up5192 3/3

README.md, docs/catalog.md, docs/ordering.md, docs/reference/asset-reference.md, docs/reference/catalog-reference.md, docs/structure.md, examples/guides/ordering.ipynb, mkdocs.yml, tests/test_asset.py, tests/test_catalog.py, tests/test_order.py, tests/test_workflow.py, up42/asset.py, up42/catalog.py, up42/workflow.py
PR 2 will include constructors from other Classes (i.e. Catalog -> Order and Asset -> Workflow).
Constructors:
Items:
=> Add ordering up5192 2/3

tests/test_workflow.py
Fix pylint issue - use-a-generator (R1729):
=> Fix use of list comprehension inside all

docs/stylesheets/extra.css, mkdocs.yml
- Incorporate changes of [mkdocstrings 0.15.0](https://mkdocstrings.github.io/changelog/#0150-2021-02-28)
Items:
For release:
=> Docs requirements upgrades

docs/ordering.md
Thanks @teoEnache 
Items:
For release:
=> add order estimate to docs guide example

examples/data-block-examples/README.md
This is the folder for the SDK data block examples. It was necessary to add an empty README for git to recognise the new directory.
Items:
For release:
=> Create empty folder and README

examples/data-block-examples/meteomatics-example.ipynb
Exanple workdlow of meteomatics block with netcdf conversion. Visualization of meteomatics data is not ideal as It's not possible to add a colorbar to explain the value ranges.
Items:
For release:
=> Meteomatics example notebook

docs/ordering.md, examples/guides/ordering.ipynb
Given https://up-42.slack.com/archives/CV9NPMRR7/p1616416876002900. CC @iliascholl-up42
=> Use delivery time filter instead of usageType

up42/__init__.py, up42/asset.py, up42/auth.py, up42/catalog.py, up42/estimation.py, up42/job.py, up42/jobcollection.py, up42/jobtask.py, up42/order.py, up42/project.py, up42/storage.py, up42/tools.py, up42/utils.py, up42/viztools.py, up42/workflow.py
In preparation for tools inheritance
- add missing variables types
- use Optional
- avoid typing Dict/List for non-detailed occurence
Items:
For release:
=> Improve variable types

tests/test_jobtask.py, tests/test_project.py
=> Fix livetests minor issue

tests/test_workflow.py, up42/job.py, up42/workflow.py
Removes explicit functionality involving order-ids, in accordance with block & product descision.
Items:
For release:
=> Remove order id up5437

tests/test_job.py, tests/test_project.py
fix live tests, setting the project limits in the live test affected the others
Items:
For release:
=> Fix max concurrent jobs live

up42/auth.py
- Small modification of retry strategy
- Small docstring & code improvements in auth module
Items:
For release:
=> Improve retry

tests/test_cli.py
Fix cli livetests
Items:
For release:
=> Fix cli livetests

up42/workflow.py
Removed feature implemented in this branch https://github.com/up42/up42-py/tree/remove_squash_geometry_up4761 but requires deprecation process. 
Items:
For release:
=> Start deprecation process  for handle_multiple_features

mkdocs.yml
=> Ignore h1 titles docs

CHANGELOG.md, mkdocs.yml
=> Small doc fixes

tests/test_catalog.py, tests/test_cli.py
=> deactivate 2 flaky livetests, investigating further

docs/ordering.md, docs/storage.md, mkdocs.yml
Clarifies documentation Getting started chapters via use of order status tracking. Adds independent user storage chapter.
Items:
For release:
=> Order storage docs improvements

up42/tools.py
Use correct staticmethod instead of pylint disable.
Items:
For release:
=> use staticmethod

coverage.svg, tests/test_storage.py, up42/storage.py
- Refactor pagination code
- fix issue query url multiple pages
- Add more tests pagination
Items:
For release:
=> Refactor pagination

up42/storage.py
Fix sorting criteria in get_orders, get_assets
Items:
For release:
=> Fix sorting criteria

docs/ordering.md, docs/storage.md, examples/guides/detailed-example.ipynb, examples/guides/ordering.ipynb
Add new sorting_criteria and limit parameters to docs examples.
Items:
For release:
=> Docs adjustments 18 0

docs/theme_override_home/main.html
=> banner update

README.md, docs/30-second-example.md, examples/guides/30-seconds-example.ipynb
Name had changed and 30 sec example was not working because of this.
-  fixed block name in 30 sec example.
Is it necessary to bump version or should the documentation be rendered automatically after the merge?
Items:
For release:
=> Fixes display name of block. 

up42/storage.py
=> add type to sortby get_orders

examples/guides/catalog.ipynb, examples/guides/ordering.ipynb
Adjustments to guide notebooks for new collections
Items:
For release:
=> Guide notebook adjustments

mkdocs.yml, requirements-docs.txt
=> Update docs dependencies

CHANGELOG.md
Items:
For release:
* [ X] Added changelog
=> bumping to V0.20.2

docs/installation.md, mkdocs.yml
Adding how to install the python SDK from conda
Items:
For release:
=> Adding conda install to docs

.gitignore, setup.py, tests/test_asset.py, tests/test_auth.py, tests/test_catalog.py, tests/test_e2e_30sec.py, tests/test_e2e_catalog.py, tests/test_estimation.py, tests/test_initialization.py, tests/test_job.py, tests/test_jobcollection.py, tests/test_order.py, tests/test_project.py, tests/test_storage.py, tests/test_utils.py, tests/test_visualization.py, tests/test_workflow.py
Some small code cleanups while on the train. Typos, remove Todos etc.
Items:
For release:
=> Code cleanup

docs/30-second-example.md, docs/storage.md
Can't reference the chapter in a normal way since it is a systemlinked file and a notebook. Not great, but using absolute http: links for these two instances now.
=> fix link detailed example

tests/test_tools.py, up42/__init__.py, up42/tools.py
=> adding get_block_coverage

tests/fixtures.py, tests/mock_data/search_params_simple.json, tests/mock_data/search_response.json, tests/test_catalog.py, tests/test_e2e_catalog.py, up42/catalog.py
- Uses host-specific catalog search endpoints
- Considers changed pagination exhaustion mechanism (no next link)
Items:
For release:
=> Host-specific catalog queries

docs/catalog.md, docs/ordering.md, examples/guides/catalog.ipynb, examples/guides/ordering.ipynb
Use new collection names
Items:
For release:
=> docs adjustments

up42/catalog.py
small docstring fix new collection names
Items:
For release:
=> small docstring fix

tests/test_catalog.py
=> adjust live test

CHANGELOG.md
Add conda update instructions to changelog.
Items:
For release:
=> conda update instructions in changelog

docs/reference/up42-reference.md, requirements-docs.txt, up42/__init__.py, up42/tools.py
Upgrade mkdocstrings to integrate the new Python handler (old general handler will be deprecated).
Items:
For release:
=> Docs library upgrade

docs/theme_override_home/main.html
Change release message
Items:
For release:
=> new message

examples/data-block-examples/pleiades-download-example.ipynb, examples/ship-identification.ipynb
Fix marketplace links in docs.
=> fix marketplace links

Makefile, up42/catalog.py
Returns empty df since from_features with empty list complains
Items:
For release:
=> Geopandas new version fix

README.md, up42/catalog.py
Order parameters docstring & non-code improvements
Items:
For release:
=> Docstrings

mkdocs.yml
=> include only specific notebooks into docs build

requirements-docs.txt
Downgrade mkdocstrings to version that supports inherited class members.
Items:
For release:
=> old mkdocstrings, new mkdocs material

docs/reference/up42-reference.md, docs/search_order.md, mkdocs.yml, up42/__init__.py
fix up42 module using all modules
Items:
For release:
=> Fix mkdocstrings usage

tests/fixtures/fixtures_auth.py, tests/test_e2e_30sec.py
Fixes live test case where auth was not available in the new init structure
Items:
For release:
=> Fix authentication indirect init

up42/auth.py
hide env string if prod, specifically only for staging
Items:
For release:
=> Shorten auth object representation

tests/test_initialization.py
reload the up42 import to avoid attached auth
Items:
For release:
=> Fix test - reload import

docs/search_order.md, docs/storage.md, examples/1_search_order_data.ipynb, examples/3_storage.ipynb
=> add asset.info to docs examples

requirements-docs.txt
Mainl to upgrade mkdocs-material to 9.0.0, improved search.
Items:
For release:
=> upgrade docs dependencies

.circleci/config.yml
Updated sonarcloud context.
Previous context and token will be deleted.
=> update sonarcloud context

docs/storage.md, docs/visualizations.md
=> small docs improvements suggested by team

tests/test_storage.py, tests/test_workflow.py, up42/auth.py
fix livetest
Items:
For release:
=> Fix livetests

CHANGELOG.md, Makefile, pylintrc, tests/mock_data/env.json, up42/catalog.py, up42/job.py, up42/jobtask.py, up42/main.py, up42/tasking.py, up42/utils.py, up42/viztools.py
Small pylint:disable cleanup, docstrings, types
Items:
For release:
=> Pylint cleanup

up42/catalog.py, up42/tasking.py, up42/utils.py, up42/workflow.py
Small cleanups geometry types and docstrings
Items:
For release:
=> cleanup order and explanations geometry types

docs/geometry_handling.md, mkdocs.yml
=> Add docs chapter geometry handling

tests/fixtures/fixtures_globals.py, tests/fixtures/fixtures_storage.py, tests/test_storage.py, up42/storage.py
Integrates the new storage stac search functionality into the `storage.get_assets` call. 
- Pagination will be handled in separate PR.
- docs changes in separate PR.
- Livetests are not yet finished due to ongoing work by Storage team. Contain TODOs.
Items:
For release:
=> Storage stac integrated

requirements-dev.txt, tests/fixtures/fixtures_asset.py, up42/auth.py, up42/job.py, up42/main.py
- Resolve new mypy testing type issues.
- Pin rest dev dependencies.
Items:
For release:
=> pin rest dev reqs

up42/asset.py
=> rename created property in class repr

tests/fixtures/fixtures_globals.py, tests/fixtures/fixtures_storage.py, tests/test_storage.py, up42/storage.py
Items:
* [x ] Ran test & live-tests
* [] Implemented (new) unit tests
For release:
=> Adding pagination storage

tests/fixtures/fixtures_globals.py, tests/test_storage.py, up42/storage.py
=> Solving mypy storage.py issues

docs/storage.md, docs/structure.md
Additional documentation for new `storage` STAC asset functionality.
Items:
For release:
=> Asset stac docs

docs/storage.md, mkdocs.yml, tests/test_storage.py, up42/storage.py
=> DOC-402: SDK v.0.28.0 (STAC asset service documentation) refinement

up42/storage.py
=> DOC-402: Doc fixes

up42/storage.py
=> HOTFIX_LintingV_0_28_0

tests/test_asset.py, tests/test_order.py
=> Updating live tests

tests/fixtures/fixtures_globals.py, tests/fixtures/fixtures_tasking.py, tests/test_auth.py, tests/test_tasking.py, up42/tasking.py
=> AT-2460 Tasking endpoints decide quotation

CHANGELOG.md, docs/reference/tasking-reference.md, docs/tasking.md, docs/theme_override_home/main.html
* Reference
* Tutorials
* Changelog
* Announcement bar
=> DOC-602: Update documentation for the Tasking class

tests/test_job.py, tests/test_main.py, tests/test_webhooks.py
Scope: Fixes failing live tests. Updates assertion.
Commented one test due to job_id not existing anymore.
Items:
For release:
=> Fix live tests

README-dev.md, docs/analytics.md, docs/catalog.md, docs/support-faq.md
Documentation changes made to support-faq.md:
- Other pages impacted:
- catalog.md
- analytics.md
- README-dev.md: fixed broken link in text.  
- Renamed page to **Support**
- **Contact**: Removed header
- **Related links**: Removed section and replaced with a **Jupyter notebooks** section
- **FAQ**: Removed all but 1 to respective pages where they are more relevant.
- "I'm having trouble installing the SDK on Windows": Removed because installation.md `For Windows (conda)` tab answers this and provides the two links.
- "Where is my config.json file with the project credentials?": Removed because authentication.md Step 3 `In a configuration file` tab shows how to create a config.json file.
- "Where can I find the default parameters for a block?": Removed because finding the default …
=> DOC-570: Rewrite SDK doc section Support and FAQ

examples/1_search_order_data.ipynb, tests/mock_data/search_params_simple.json, tests/test_catalog.py, tests/test_e2e_catalog.py, up42/catalog.py
=> [AT-2477] Removing sortby in search catalog method

examples/tasking/tasking-example.ipynb
=> Edit list numeration

.github/workflows/mkdocsdeploy.yml
=> BUGFIX Upgrading python version MkDocs

.circleci/config.yml, requirements-dev.txt, requirements-docs.txt, requirements-viz.txt, requirements.txt, sonar-project.properties, tests/fixtures/fixtures_asset.py, tests/fixtures/fixtures_globals.py, tests/fixtures/fixtures_project.py, tests/mock_data/order_data/archive_order_info.json, tests/mock_data/order_data/tasking_order_info.json, tests/test_asset.py, tests/test_catalog.py, tests/test_jobcollection.py, tests/test_tasking.py, up42/utils.py
Jira ticket [here](https://up42.atlassian.net/browse/AT-3000) and [here ](https://up42.atlassian.net/browse/AT-3141)
Also updated python version for SonarCloud and live test circleCI image
Items:
For release:
=> [AT-3000] [AT-3141] update download file name; pin dependencies

docs/analytics.md, docs/support-faq.md
Documentation changes made to analytics.md and support.md:
**analytics.md**
- **Step 1. Create and populate a workflow**: Updated text about processing block limits in a workflow
- Added a **Troubleshooting** section with information about the number of blocks allowed in a workflow.
**support.md**
- Removed links to mosaicking and training materials notebooks
=> DOC-632: Limit on the number of blocks

.github/CODEOWNERS
=> update CODEOWNERS file to reflect github-governance#441

tests/fixtures/fixtures_asset.py, tests/fixtures/fixtures_globals.py, tests/test_asset.py, tests/test_auth.py, tests/test_order.py, up42/asset.py, up42/auth.py, up42/stac_client.py, up42/storage.py, up42/utils.py
Jira Ticket [here](https://up42.atlassian.net/browse/AT-3079).
Scope: Adds functionality to download STAC asset on up42's Asset object.
Items:
For release:
=> [AT-3079] Add functionality to download STAC assets

tests/test_catalog.py
Jira ticket [here](https://up42.atlassian.net/browse/AT-3454)
Relevant slack thread [here.](https://up-42.slack.com/archives/CV9NPMRR7/p1695113492969929)
Data team is also aware.
Scope: Handles multiple datetime format in test.
Items:
For release:
=> [AT-3454] handle multiple datetime formats

docs/reference/order-reference.md
=> AT-4038 Fix broken link in order reference

README.md
Jira ticket [here.](https://up42.atlassian.net/browse/AT-3877).
Scope: 
-  Updated example to show-case most recent functionalities. 
Items:
For release:
=> [AT-3730] Update readme example

.github/workflows/mkdocsdeploy.yml, docs/README.md, examples/asset/asset-example.ipynb
=> Fix docs deployment

.circleci/config.yml, tests/test_auth.py, tests/test_utils.py, up42/auth.py, up42/main.py, up42/utils.py, up42/workflow.py
=> Extract json loading

tests/test_catalog.py, tests/test_order.py, up42/order.py
Migrating place order to V2 endpoint
Items:
For release:
=> [AT-4219] Migrating place order to V2 endpoint

up42/order.py
=> BUGFIX Allowing user set displayName for Tasking orders

CHANGELOG.md, pyproject.toml, tests/http/test_session.py, up42/http/session.py
Porting resilient and authenticated session
Items:
For release:
=> AT-4866 Resilient and authenticated session

CHANGELOG.md, pyproject.toml
Fixing changelog and version after latest merge
Items:
* [] Ran test & live-tests
For release:
=> AT-4886 Fix changelog and version

CHANGELOG.md, pylintrc, pyproject.toml, tests/conftest.py, tests/fixtures/fixtures_auth.py, tests/fixtures/fixtures_jobcollection.py, tests/http/test_oauth.py, tests/test_auth.py, up42/auth.py, up42/http/config.py, up42/http/oauth.py, up42/tasking.py
Drop linting exclusion for auth and conf files
Items:
For release:
=> AT-4080 Enable pylint for auth and conf files

CHANGELOG.md, pylintrc, pyproject.toml, tests/fixtures/fixtures_storage.py, tests/test_storage.py, tests/test_tools.py, up42/storage.py, up42/tools.py
Jira ticket [here.](https://up42.atlassian.net/browse/AT-3970)
Scope: enable pylint for all storage, tools, and host files
Items:
For release:
=> [AT-3970] enable pylint for storage, host, and tools

CHANGELOG.md, docs/macros.py, pylintrc, pyproject.toml, tests/test_utils.py, up42/utils.py
Jira ticket [here.](https://up42.atlassian.net/browse/AT-3970)
Scope: enable pylint for all macros and utils files
Items:
For release:
=> [AT-3970] enable pylint for utils and macros

CHANGELOG.md, docs/theme_override_home/main.html, pyproject.toml
What's new:
- Fixed inadvertent titles and tags removals during asset metadata updates.
- Dropped unneeded `auth::env` property and the corresponding tests.
- Generalized new authentication stack to cover account authentication case.
- Added new components within the HTTP layer to facilitate future enhancements in authentication and request processes.
- Adjusted most of the code in accordance with pylint checks.
Items:
For release:
=> release version 0.37.0

CHANGELOG.md, pyproject.toml, tests/http/test_oauth.py, up42/http/config.py, up42/http/oauth.py
Detection of credentials settings based on supplied credentials
Items:
For release:
=> [AT-4915] Settings detection based on credentials

CHANGELOG.md, pyproject.toml, tests/http/test_oauth.py, up42/http/config.py, up42/http/oauth.py
=> [AT-4915] Fail with a domain error if credentials are wrong

CHANGELOG.md, pyproject.toml, up42/initialization.py, up42/workflow.py
Updating the deprecation dates for `Projects`, `Workflows`, and `Jobs`
Items:
For release:
=> AT4944 Updating deprecation dates

CHANGELOG.md, docs/macros.py, pyproject.toml, tests/fixtures/fixtures_auth.py, tests/fixtures/fixtures_globals.py, tests/http/test_client.py, tests/http/test_oauth.py, tests/test_auth.py, tests/test_initialization.py, up42/__init__.py, up42/auth.py, up42/catalog.py, up42/http/config.py, up42/http/oauth.py, up42/initialization.py, up42/main.py, up42/viztools.py
- Dropped project id and api key based authentication in `main.py`, `auth.py`, `http/oauth.py` and `http/client.py`
- Adapted tests and fixtures
- Dropped viztools.py
Items:
For release:
=> [PT-4349] Drop project authentication

CHANGELOG.md, pyproject.toml
Scope:
- Updated version
- Added changelog
Items:
For release:
=> Release v1.0.0 - update version and add changelog entry

CHANGELOG.md, pyproject.toml, up42/http/oauth.py
[PT-5257](https://up42.atlassian.net/browse/PT-5257?atlOrigin=eyJpIjoiZmZkYWIzNjVkZjkwNGNkODllODdiM2U2YzRhYjY2YTEiLCJwIjoiaiJ9)
Items:
For release:
[PT-5257]: https://up42.atlassian.net/browse/PT-5257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> adding thread lock for token refresh

CHANGELOG.md, pyproject.toml
=> Bump version 1.0.2

CHANGELOG.md, pyproject.toml
Bump to version 1.0.3
Items:
For release:
=> bump to version 1.0.3

CHANGELOG.md, pyproject.toml, tests/test_processing.py, up42/processing.py
Processing cost evaluation
Items:
For release:
=> [PT-5055] Processing cost evaluation

CHANGELOG.md, poetry.lock, pyproject.toml
Updating geopandas to all versions from 0.0.0 to <1.0.0
Items:
For release:
=> PT5290 update geopandas

CHANGELOG.md, pyproject.toml, tests/test_processing.py, up42/processing.py
Job template execution with modelless job data class
Items:
For release:
=> [PT-5055] Job template execution

CHANGELOG.md, pyproject.toml, tests/test_processing.py, tests/test_utils.py, up42/processing.py, up42/utils.py
Query jobs via iterator
Items:
For release:
=> [PT-4557] Query jobs

CHANGELOG.md, pyproject.toml, tests/test_base.py, tests/test_processing.py, up42/base.py, up42/processing.py
=> PT5353 Adding collection results to processing Job

CHANGELOG.md, pyproject.toml, tests/http/test_oauth.py, tests/test_processing.py, up42/http/oauth.py, up42/processing.py
- Support deepcopy for oauth to be compliant with pystac client
- Finalize job query parameters
Items:
For release:
=> [PT-5377] Support deep copy for auth

CHANGELOG.md, pyproject.toml
Update changelog and bumping version to release 1.0.4
Items:
For release:
=> release version 1.0.4

CHANGELOG.md, pyproject.toml, up42/__init__.py
Export JobStatus to up42 namespace.
For release:
=> Export JobStatus to up42 namespace

CHANGELOG.md, pyproject.toml, tests/test_processing_templates.py, up42/processing_templates.py
Update processing template names according to Product approval.
For release:
=> [PT-5381] Update processing template names

CHANGELOG.md, pyproject.toml, tests/test_processing.py, up42/processing.py
See changelog.
Items:
For release:
=> [PT-5409] Processing bugfixes

CHANGELOG.md, pyproject.toml, tests/test_processing.py, up42/processing.py
See changelog.
Items:
For release:
=> Processing bugfixes

CHANGELOG.md, pyproject.toml
1.1.0 SDK Release
Items:
For release:
=> Adding 1.1.0 changelog and version bump

CHANGELOG.md, docs/PULL_REQUEST_TEMPLATE.md, pyproject.toml, tests/fixtures/fixtures_auth.py, tests/fixtures/fixtures_globals.py, tests/http/test_oauth.py, tests/test_auth.py, tests/test_base.py, tests/test_host.py, up42/auth.py, up42/host.py, up42/http/config.py, up42/http/oauth.py
=> [PT-4506] Improve OAuth flow

CHANGELOG.md, pyproject.toml, tests/fixtures/fixtures_catalog.py, tests/test_catalog.py, up42/base.py, up42/catalog.py, up42/initialization.py, up42/webhooks.py
=> Clean up product glossary usage

CHANGELOG.md, pyproject.toml, up42/catalog.py
=> Fix type alias

CHANGELOG.md, pyproject.toml, tests/test_auth.py, tests/test_catalog.py, up42/auth.py, up42/catalog.py
=> [PT-5447] Improve coverage of catalog quicklooks download

CHANGELOG.md, pyproject.toml, up42/catalog.py
=> [PT-5513] Deprecate CatalogBase.get_data_product

CHANGELOG.md, pyproject.toml, tests/test_processing.py, up42/processing.py
=> [PT-5519] EULA acceptance check for processing templates

CHANGELOG.md, README.md, pyproject.toml, tests/test_catalog.py, up42/catalog.py
=> [PT-5506] Drop data products retrieval

CHANGELOG.md, pyproject.toml, tests/test_processing_templates.py, up42/processing_templates.py
=> [PT-5542] Drop Spacept augmentation

CHANGELOG.md, pyproject.toml, tests/test_catalog.py, up42/__init__.py, up42/catalog.py, up42/tasking.py
=> [PT-5505] ProductGlossary V2 get_collections

CHANGELOG.md, pyproject.toml, tests/test_order.py, up42/order.py
=> Improve order test coverage

CHANGELOG.md, pyproject.toml, tests/test_order.py, up42/order.py
=> improve order test coverage - track_status, estimate, and place methods

CHANGELOG.md, pyproject.toml, tests/test_utils.py, up42/catalog.py, up42/tasking.py, up42/utils.py
=> [PT-5597] Remove and inline utils::autocomplete_order_parameters

CHANGELOG.md, pyproject.toml, tests/test_catalog.py, up42/catalog.py
=> [PT-5597] (2) Updating catalog `construct_search_parameters`

CHANGELOG.md, pyproject.toml, tests/test_catalog.py, up42/catalog.py
=> [PT-5597] (3) Catalog::search testing coverage

CHANGELOG.md, pyproject.toml, up42/asset.py
=> [BUGFIX] Fix Asset_id property type

CHANGELOG.md, pyproject.toml, tests/test_base.py, up42/base.py
=> [PT-5671] Updating `base::get_credits_balance` from base.py

CHANGELOG.md, pyproject.toml, tests/test_storage.py, up42/storage.py
=> [Bug-recovery] Restore old behavior for Storage::get_orders

CHANGELOG.md, pyproject.toml, tests/test_catalog.py, tests/test_initialization.py, tests/test_order.py, tests/test_storage.py, up42/initialization.py, up42/order.py, up42/storage.py
=> [PT-5886] Simplify order construction

CHANGELOG.md, pyproject.toml, tests/test_catalog.py, tests/test_initialization.py, tests/test_order.py, up42/order.py
=> [PT-5886] Fix order placement and reduce order testing dependencies

CHANGELOG.md, pyproject.toml, tests/test_storage.py
=> [PT-5886] Reduce order testing dependencies for storage module

CHANGELOG.md, pyproject.toml, tests/test_tasking.py, up42/__init__.py, up42/tasking.py
=> [PT-5889] Quotation active record class

CHANGELOG.md, pyproject.toml, tests/test_glossary.py, up42/catalog.py, up42/glossary.py
=> [PT-5897] Data product schema

CHANGELOG.md, pyproject.toml, tests/test_glossary.py, up42/catalog.py, up42/glossary.py
=> [PT-5897] Host search method

CHANGELOG.md, pyproject.toml, tests/test_glossary.py, up42/catalog.py, up42/glossary.py, up42/utils.py
=> [PT-5897] Scene quicklook

CHANGELOG.md, pyproject.toml, up42/glossary.py, up42/utils.py
=> [PT-5897] Enable access to authenticated image files

CHANGELOG.md, pyproject.toml, tests/test_asset.py, up42/asset.py, up42/catalog.py, up42/initialization.py, up42/order.py, up42/storage.py
=> [PT-5901] Asset data class

CHANGELOG.md, pyproject.toml, tests/test_asset.py, tests/test_initialization.py, tests/test_order.py, tests/test_storage.py, up42/__init__.py, up42/asset.py, up42/initialization.py
=> [PT-5901] Reduce asset test dependencies

CHANGELOG.md, pyproject.toml, tests/test_asset.py, up42/asset.py, up42/initialization.py
=> [PT-5901] Asset fields

CHANGELOG.md, pyproject.toml, tests/test_asset.py, up42/asset.py
=> [PT-5901] Asset save method

CHANGELOG.md, pyproject.toml, up42/initialization.py, up42/order_template.py, up42/tasking.py
=> Optional order template tags and deprecation of legacy methods

CHANGELOG.md, pyproject.toml, tests/test_stac.py, up42/__init__.py, up42/asset.py, up42/stac.py
=> File provider for STAC assets

CHANGELOG.md, pyproject.toml, up42/asset.py, up42/stac.py
=> Fix file provider image file session

CHANGELOG.md, pyproject.toml, tests/test_asset.py, tests/test_base.py, up42/__init__.py, up42/asset.py, up42/base.py
=> Core stac client and asset file property

CHANGELOG.md, pyproject.toml, tests/test_stac.py, up42/stac.py
=> Update Item tags

.github/CODEOWNERS
=> Allow teams to bump version and update changelog

CHANGELOG.md, pyproject.toml, tests/test_stac.py, up42/stac.py
=> PT-5398  UP42 Extension Provider

pyproject.toml
=> bump version in pyproject.py

CHANGELOG.md, pyproject.toml, tests/constants.py, tests/test_stac.py, up42/stac.py
=> PT-6054 Adjust stac FileProvider class to check for generic endpoint

CHANGELOG.md, pyproject.toml, up42/asset.py
=> PT-5896 Populate AssetSorting with possible sorting fields

CHANGELOG.md, pyproject.toml, tests/test_processing.py, up42/processing.py
=> PT-6051/handle unavailable processes

CHANGELOG.md, pyproject.toml, tests/test_order.py, up42/order.py
=> Remove info from order representation

CHANGELOG.md, pyproject.toml, tests/test_glossary.py, up42/glossary.py
See changelog.
[ARC-2974]
Checklist:
[ARC-2974]: https://up42.atlassian.net/browse/ARC-2974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ARC-2974 - Adjust Provider::search 

.github/CODEOWNERS
Adding catalog team to sdk code owners
=> Add catalog team to code owners

CHANGELOG.md, pyproject.toml
=> Clean up the changelog to adhere to the new release process

CHANGELOG.md, pyproject.toml, tests/test_tasking.py, up42/__init__.py, up42/tasking.py
=> [TS-1719] Feasibility active record class

CHANGELOG.md, pyproject.toml, tests/test_processing_templates.py, up42/processing_templates.py
Tracked in https://up42.atlassian.net/browse/PT-6002
See changelog.
Checklist:
=> PT-6002 Add upsampling-ns-sentinel process template

CHANGELOG.md, pyproject.toml, tests/test_stac.py, up42/__init__.py, up42/stac.py
=> [PT-5400] add bulk deletion

CHANGELOG.md, pyproject.toml, tests/test_stac.py, up42/stac.py
=> Fix collection item retrieval

CHANGELOG.md, pyproject.toml, tests/test_processing_templates.py, up42/processing_templates.py
=> PT-6362 Add Detection Change Simularity template

CHANGELOG.md, pyproject.toml, tests/test_order.py, up42/order.py
=> DPT-747: Add missing properties to TaskingOrderDetails
