setup.py, up42/workflow.py
Avoid mutating input_parameters, to enable user to run it first as a test query, then as a normal job without problems.
=> Fix test query

requirements-dev.txt, tests/test_job.py, tests/test_utils.py, up42/job.py, up42/jobtask.py, up42/utils.py
- Removes the range header download (actually not the solution for gcs inconsistencies).
- Uses chunks.
- Adds (skipped) huge download to test gcs 2min treshold (test successfull).
=> Remove gcs range download

.circleci/config.yml
Ignores github-pages branch in Circleci (docs branch that only contains the hmtl pages).
https://circleci.com/docs/2.0/configuration-reference/#full-example
=> ignore gh-pages

README.md, docs/30-seconds-example.md, examples/30-seconds-example.ipynb, tests/test_workflow.py, up42/tools.py, up42/workflow.py
Enables to add workflow tasks by block_name & block_display_name (in addition to block_id) or combinations.
input_tasks = ['a2daaab4-196d-4226-a018-a810444dcad1',
'4ed70368-d4e1-4462-bef6-14e768049471']
input_tasks = ["sobloo-s2-l1c-aoiclipped", "tiling"]
input_tasks = ["Sentinel-2 L1C MSI AOI clipped",
"Raster Tiling"]
Makes the docs examples a bit clearer as `[blocks['sobloo-s2-l1c-aoiclipped'], blocks['sharpening']]` is no longer required, will adjust later.
=> Block name for workflow task

docs/catalog.md, examples/catalog.ipynb, requirements-dev.txt, tests/mock_data/search_params_simple.json, tests/test_catalog.py, up42/__init__.py, up42/catalog.py
- Instead of the image `provider` the user selects the `sensor` as argument for download_quicklooks. Much easier as the sensor needs to be specified for catalog search anyway and the user might not know about the provider. 
- Also removes the backend string as not required.
=> Avoid provider arg catalog quicklook

tests/test_project.py, tests/test_workflow.py, up42/project.py, up42/workflow.py
- Adds Project().get_jobs() as getjob is actually unrelated to workflow and should be accessible at this level.
- Adds a filter to Workflow.get_jobs() to only return the jobs that are associated with the workflow object.
=> Get jobs for projects

coverage.svg, tests/context.py, tests/test_job.py, tests/test_utils.py, up42/job.py, up42/utils.py
- Uses rasterio warped vrt to ensure required crs, removes `read_raster_4326`from utils. Had totally forgotten about it.
- Adds mock test .map_results().
=> Use warped vrt for .map_results

coverage.svg, tests/test_workflow.py, up42/workflow.py
We found in https://github.com/up42/up42-py/pull/101 that the construct parameters is currently not supporting the creation of job parameters that include only scene ids (without a geometry). This change ensures that the parameters are generated even when no geometry is passed.
=> Allow passing of only scene_ids in construct_parameters

coverage.svg, docs/reference/jobcollection.md, mkdocs.yml, tests/context.py, tests/fixtures.py, tests/test_jobcollection.py, tests/test_workflow.py, up42/jobcollection.py, up42/workflow.py
This is the first out of three (1/3) PRs intended to provide the parallel job run feature in the python SDK. We will work on the feature branch `add-parallel-jobs` and only when after all 3 PRs are merged we will make a PR to master for deployment.
Handles three cases:
1. Mapping n x Scene IDs with n x Geometries
2. Mapping n x Time Intervals with n x Geometries
3. Mapping n x Scene IDs
Requires merge of https://github.com/up42/up42-py/pull/102 for passing tests.
=> Add parameters mapping

.gitignore, up42/job.py, up42/utils.py
Adding a temporary solution for downloading output without unpacking them. Specifically important for formats such as SAFE, etc ...
=> Add unpacked dl option

tests/test_job.py, up42/job.py, up42/utils.py
Adds support for the additional geojson file of some blocks (ship-identification etc.) to `.map_results()`. If a dedicated geojson file exists in the output files this is picked over the data.json for visualization.
=> Handle additional geojson output

tests/test_project.py, tests/test_workflow.py, up42/jobcollection.py, up42/project.py, up42/tools.py, up42/workflow.py
- .get_jobs returns Jobcollection (for Project & Workflow)
- Enable jobcollection.plot()
- Simplify Jobcollection download
- fix run_parallel_jobs naming schema
=> Job collection improvements

coverage.svg, pylintrc, tests/fixtures.py, tests/test_job.py, tests/test_jobcollection.py, tests/test_project.py, tests/test_workflow.py, up42/job.py, up42/jobcollection.py, up42/utils.py
- Adds flag (defaults to True) to download_results in order to merge all data.json from a JobCollection into a single data.json with updated `up42.data_path`
- Keep folder structure when unpacking results from tar file
- Adds tests for unpacked result download and DIMAP file download
- Ignore not-callable temporarily
=> Merge jobcollection results

coverage.svg, docs/reference/jobcollection.md, tests/fixtures.py, tests/test_job.py, tests/test_jobtask.py, tests/test_project.py, tests/test_workflow.py, up42/__init__.py, up42/auth.py, up42/catalog.py, up42/cli.py, up42/job.py, up42/jobcollection.py, up42/jobtask.py, up42/project.py, up42/tools.py, up42/workflow.py
Currently the maximum number of concurrent jobs is a project setting in UP42. This PR makes necessary changes that check the maximum number of concurrent jobs in settings and raises a ValueError when users select a higher number in the run_parallel_job method. This avoids unhandled API errors when the number of concurrent jobs is exceeded.
In addition:
=> Add limitation for max concurrent jobs

tests/test_jobtask.py, up42/catalog.py, up42/job.py, up42/jobtask.py
When using the default output dir, Jobtasks were downloaded to the jobs folder. When downloading multiple jobtasks this lead to overwritten files. Now downloading to cwd/project_id/job_id/jobtask_id.
=> Download jobtasks to subfolder - up4865

docs/reference/cli.md, requirements-dev.txt, setup.py, tests/test_cli.py, up42/cli.py
Updates the main module of the CLI to be called up42. This allows mkdocs-click to properly display the commands in the reference. Consequence of issue answer from mkdocs-click package https://github.com/DataDog/mkdocs-click/issues/6.
=> Main to up42 name in CLI

tests/test_job.py, tests/test_utils.py, up42/utils.py
=> Fix download results up4867

tests/fixtures.py, tests/test_initialization.py, tests/test_job.py, tests/test_jobtask.py, tests/test_workflow.py, up42/__init__.py, up42/job.py, up42/jobcollection.py, up42/jobtask.py, up42/project.py, up42/utils.py, up42/workflow.py
- Simplifies the object __repr__ to only include relevant information. The verbose output also blew up the logger messages and made it difficult to work with Jobcollection/lists of objects (Also suggested in feedback). `.info` for the full metadata as json, will also be made clearer in the docs.
- `get_workflow_tasks(basic=True)` now returns task_name: block_version instead of task_name: task_id (which is never used anyway).
- Adds workflow_tasks property
- Adds workflow tasks to workflow __repr__
- Simplifies the logger message format & truncates in case of extremely log messages (e.g. large collections).
Before/After:
=> Less verbose repr and logger

docs/reference/job.md, docs/reference/jobcollection.md, docs/reference/jobtask.md, docs/reference/project.md, docs/reference/up42.md, docs/reference/workflow.md, mkdocs.yml, up42/__init__.py
Last PR before new version.
- Add object initialization at top of page for each object to code reference
- Add up42 base import chapter to code reference (currenty only contains the object initializations, to be extended with get_blocks() etc when inheritance is clearer).
- Remove `order_ids` from `up42.initialize_job`, makes no sense, only at Job creation.
=> Code reference improvements

tests/mock_data/search_params_simple.json, tests/test_catalog.py, up42/catalog.py
Catalog search sobloo provider data block names were changed on backend, broke the catalog search for sobloo sensors. This fixes it, users need to update though, no backwards compatability.
Longer term data-api team will implement api endpoint to query the provider:data_blocks mappings, then the mapping in the SDK can be removed.
=> Fix catalog data blocks up4982

coverage.svg, tests/test_auth.py, up42/auth.py
With newly introduced rate limiting in the UP42 API, this PR handles retrying in cases where the rate limit is exceed by using a exponential backoff strategy with jitter (see [tenacity docs](https://tenacity.readthedocs.io/en/latest/api.html#tenacity.wait.wait_random_exponential)).
=> Add exponential backoff up4980

up42/viztools.py
Enables band selection in `plot_results` and `map_results`. Also required for new default examples.
x           |  y |  z
:-------------------------:|:-------------------------:|:-------------------------:
=> Plotting bands

docs/theme_override_home/main.html, mkdocs.yml, up42/workflow.py
- Adds explicit description of how to use custom blocks with the SDK to code reference (required for support case).
- Removes broken notebook download buttons (folder with links is still linked on example page).
Items:
For release:
=> Use custom block docs

README.md, docs/30-second-example.md, examples/guides/30-seconds-example.ipynb, examples/guides/detailed-example.ipynb, mkdocs.yml, requirements-dev.txt
- Fixes SDK examples, sentinelhub block display name were renamed. sdk.up42.com already adjusted.
- Removes unneccessary docs plugin.
Items:
For release:
=> Renamed example blocks

docs/reference/cli-reference.md
Plugin mkdocs-macros was "disappearing" the CLI reference. This seems like it's due to [Jinja like statements ](https://mkdocs-macros-plugin.readthedocs.io/en/latest/advanced/#how-to-prevent-interpretation-of-jinja-like-statements) in the output HTML. Adding a raw enclosure in the call to mkdocs-click plugin fixes the issue.
Items:
* [na] Ran test & live-tests
* [na] Implemented (new) unit tests
* [na] Removed credentials
* [na] Removed argument pointing to staging
=> Fix reference docs for CLI

.circleci/config.yml, .github/workflows/mkdocsdeploy.yml, Makefile, requirements-dev.txt, requirements-docs.txt, tests/test_e2e_30sec.py, tests/test_e2e_catalog.py, tests/test_job.py, tests/test_jobtask.py
Add Circle CI config to enable live testing and deployment in CI. Fix a couple of issues in tests. 
In addition add Github Actions to deploy docs in master.
**What changes from now on:**
- Any deployment of a new package version should be done via CircleCI with the new approve to deploy in master
- Live tests will be run every night at 12AM.
- Any merge into master that changes the documentation will trigger a deployment of the docs
Items:
* [na] Removed credentials
* [na] Removed argument pointing to staging
* [na] Updated [documentation](sdk.up42.com)
=> Add CircleCI and GitHub action up4621

up42/__init__.py
Disables pylint error in ci livetest run. Could not reproduce locally (with updated mypy), functions works as expected, guess just mypy not understanding the full function.
Items:
For release:
=> disable pylint no-member in ci - up5330

examples/data-block-examples/oneatlas-worlddem-12m-example.ipynb
Adds data access notebook example for OA worlddem block.
Items:
For release:
=> add OA worlddem notebook

tests/test_job.py, up42/job.py
This PR addresses and solves the following ticket https://up42.atlassian.net/browse/UP-5307?atlOrigin=eyJpIjoiMzA4NmZlODMyYTEyNDEwM2E2OGE3N2QwNDllNDg4NzMiLCJwIjoiaiJ9. The cancel_job functions was failing, apparently because the endpoint has changed (see here https://docs.up42.dev/openapi/swagger-ui/?urls.primaryName=backend-core#/jobs-controller/cancelJob).
A live test was added to ensure that the status from the job changes from RUNNING to CANCELLED.
Items:
For release:
=> Bug cancel job up5307

tests/mock_data/search_params_simple.json, up42/catalog.py
While working on https://github.com/up42/mosaicking I noticed the display blocks were not placed in the catalog search parameters. This PR addresses that.
Items:
* [na] Implemented (new) unit tests
* [na] Updated [documentation](sdk.up42.com)
=> Add display blocks reference in Catalog

setup.py
After feedback & testing found that there is an issue when installing the package dependencies (geopandas) with Python 3.9. Investigating further soon.
Items:
For release:
=> limit to <3.9

docs/macros.py, tests/test_jobcollection.py, up42/jobcollection.py
remove deprecated jobcollection.get_job_info & get_job_status
Items:
For release:
=> remove deprecated jobcollection.get_job_info & get_job_status

tests/fixtures.py, tests/test_job.py, tests/test_project.py, up42/project.py
Integrate new payload structure to new post request for updating the projecting settings. Replace hardcoding of value ranges with project setting request.
Items:
For release:
=> New project settings post and payload up5366

tests/fixtures.py, tests/test_auth.py, tests/test_project.py, up42/asset.py, up42/auth.py, up42/job.py, up42/jobtask.py, up42/order.py, up42/project.py, up42/workflow.py
Simplifies class instantiation with auth-mock by removing the additional "auth-mock-without-info-call" mechanism. Not relevant anymore, was mainly for avoiding code duplication of the additional info mock request in every test (mock now in the fixtures anyway) and to be explicit about some single requests (not actually important).
Items:
For release:
=> Remove get info from fixtures up4296

tests/test_project.py
fix livetests - project settings lengths is fixed
Items:
For release:
=> fix livetests - project settings lengths is fixed

.circleci/config.yml, tests/test_asset.py, tests/test_job.py, tests/test_jobtask.py, tests/test_utils.py
- Fixes pylint errors due to new version
- Disables pylint/mypy for daily ci livetests
Items:
For release:
=> Pylint disable for livetests up5530

docs/macros.py, up42/__init__.py, up42/asset.py, up42/auth.py, up42/catalog.py, up42/estimation.py, up42/job.py, up42/jobcollection.py, up42/jobtask.py, up42/order.py, up42/project.py, up42/storage.py, up42/tools.py, up42/workflow.py
Fully deprecates the Tools module inheritance  in the other classes (after deprecation process). The tools functions will only be available from the `up42` import object.
Items:
For release:
=> Deprecate tools inheritance

up42/cli.py
Don't use deprecated tools access via catalog in cli livetest
Items:
For release:
=> fix cli livetest

tests/test_cli.py, tests/test_job.py, up42/cli.py
Skip test_cancel_job_live due to server flakiness, to avoid ci livetests failing.
Items:
For release:
=> skip test_cancel_job_live

requirements-dev.txt
Adds type-stubs packages (which are used with mypy) as requirements. Mypy automatically installs [typeshed](https://github.com/python/typeshed/blob/master/README.md), but apparently type-stubs for third packages are external now or weren't required before.
Also pinning mypy&pylint to require less changes. We can update intentionally from time to time.
Items:
For release:
=> Update pin mypy

up42/utils.py
Currently, the SDK downloads the entire file into memory before storing it on disk. This causes out-of-memory issues for downloads larger than the available RAM size (this is an actual problem for our latest order).
This can be simply mitigated by enabling stream download.
=> Limit memory usage for large file downloads

Makefile
Latest changes are not passing circleci test (when going to prod), see here https://app.circleci.com/pipelines/github/up42/up42-py/1163/workflows/1b069335-94b1-405c-9407-a0b7143cdbf3/jobs/1179/steps. Changes only entail a new jupyter notebook example.
The error is related to an existing file with the same name. I got solution from here https://stackoverflow.com/questions/52016336/how-to-upload-new-versions-of-project-to-pypi-with-twine/52130985.
=> Add skip existing to makefile dist upload

tests/context.py, tests/test_utils.py, tests/test_workflow.py, up42/catalog.py, up42/utils.py, up42/workflow.py
- Use the new time formatting options (iso, datetime) from https://github.com/up42/up42-py/pull/244 also in catalog search
- Move time formatting logic to utils module to simplify code structure
Items:
For release:
=> Iso time for catalog and workflow up5631

coverage.svg, up42/catalog.py
SDK used an additional geometry filtering for catalog search results, to filter results out that were not actually touching the search geomety. Instead will be ticketed with backend and removed, since it is also interfering with the catalog pagination testing.
Items:
For release:
=> remove geometry filtering for catalog search results

coverage.svg, tests/fixtures.py, up42/project.py
Speed up project.create_workflow(..., use_existing=True) by using the json return of all workflows in the project to compare with the workflow that is supposed to be created. Previously the workflow object of each workflow was used for the comparison which takes much longer due to each additional workflow.info call.
Items:
For release:
=> Speed up create workflow existing up5736

mkdocs.yml, requirements-docs.txt
Removes mkdocs-exclude-search plugin, which was required for excluding specific CLI chapters (CLI was removed).
Items:
For release:
=> remove exclude-search plugin

coverage.svg, pylintrc, tests/fixtures.py, tests/test_storage.py, up42/storage.py
- Uses the recently introduced API pagination for get_orders. 
- Adds limit parameter to get_assets and get_orders.
- Refactors the pagination helper function to be more efficient when using a limit < the pagination size.
TODO: Update documentation guide chapter examples.
Items:
For release:
=> Use pagination in get_orders - up5726

tests/test_storage.py, up42/storage.py
Followup to https://github.com/up42/up42-py/pull/265, adds sorting criteria and sorting order parameters to storage.get_assets and storage.get_orders.
This requires more mocktests, but a lot of effort since the sorting criteria would change the server response. Putting as Draft PR review for now.
Items:
For release:
=> Add sortorder and criteria get assets orders up5745

up42/jobtask.py
use _info in jobtask info to avoid additional API calls.
Items:
For release:
=> use _info in jobtask info

examples/guides/30-seconds-example.ipynb
Attempt at fixing the 30 seconds example python notebook that was changed accidentally.
json in examples/guides/30-seconds-example.ipynb has now been validated.
Items:
For release:
=> Fix failling publish docs

coverage.svg, tests/fixtures.py, tests/test_auth.py, up42/auth.py, up42/project.py
- Resolves issue of unintended token renewals by using wrong tenacity retry `after` syntax
- Further limits retry mechanism to connection error, token timeout, rate limit
- Refactors retry code
- Increases test coverage on retry requests
- Removes option to disable retry for unittests (this was implemented to avoid unintended side effects in tests but does more harm than good).
Items:
For release:
=> Refactor retry mechanisms

docs/catalog.md, docs/ordering.md, tests/fixtures.py, tests/mock_data/search_params_simple.json, tests/test_catalog.py, tests/test_e2e_catalog.py, up42/catalog.py
- Adds support for UP42 data collections
- Breaking change: Adjust catalog.construct_parameters to use collections instead of sensors (already removed from API).
Items:
For release:
=> Add collection support up5754

up42/auth.py
Neccessary as token timeout can also raise base Requestsexception with 401.
Items:
For release:
=> add base requestsexception with 401 to token renewal check

tests/test_catalog.py
catalog order price estimation assertion changed due to filter changes
Items:
For release:
=> fix livetest assertion

tests/test_catalog.py
Quicklook for image-id not available anymore, update.
Items:
For release:
=> use updated image id for quicklook test

tests/fixtures.py, tests/test_job.py, up42/job.py
The support team requested that the SDK outputs credit usage for each job. 
Two questions:
- What else would I need to update in the documenattion. The method doc is automatically uploaded to the docs. 
- What happens if the job status is "Running". This could fail right? The download_results method doesn't account for this either, so I'm wondering what the behaviour is here.
Items:
For release:
=> Add get job credits methods and tests

tests/test_auth.py, up42/auth.py
Set user-agent instead of custom header to enable proper API/SDK tracking.
Items:
For release:
=> user agent instead of custom header

tests/test_order.py, tests/test_project.py, up42/project.py
Adds limit parameter and sorting oprtions to `project.get_jobs`.
Items:
For release:
=> add limit and sorting - get_jobs

docs/30-second-example.md, tests/test_catalog.py, tests/test_utils.py, up42/__init__.py, up42/tools.py, up42/utils.py
- Fixes an issue where using a MultiPolgon geometry in construct_parameters failed. Now it is included in the possible cases. 
- Also separates the UP42 geometry requirement validation in a separate function.
- Some small code & error message improvements.
Items:
For release:
=> Geometry validation int32

.circleci/config.yml, requirements-viz.txt, requirements.txt, setup.py, up42/__init__.py, up42/tools.py, up42/viztools.py
Makes the dependencies for the vizualizations optional. Adds `pip install up42-py[viz]` installation option.
To check: How this affects the conda installation.
Items:
For release:
=> Optional viz dependencies int54

tests/context.py, tests/fixtures.py, tests/test_asset.py, tests/test_job.py, tests/test_utils.py, up42/asset.py, up42/job.py, up42/jobtask.py, up42/utils.py
Ensures that assets from user storage that originate from archive orders (zip format) are correctly unpacked, even if they don't contain the up42-inherent "output" topfolder.
- Also slightly refactors the unpacking functions. 
- Checks the download url for the archive format for the filename of the unpacked download variant.
- Moves livetests under mocktests (wasnt the case in jobtest module yet).
Adds new testing env variable "TEST_UP42_ASSET_ID_2_zip", already updated in CI.
Items:
For release:
=> Gcs download unpacking improvements

tests/test_auth.py, up42/auth.py
Simplify API error message surfacing. Just passes through the original API error message, no additional formatting. This also surfaces the "details" key which is contained in some API error messages.
Items:
For release:
=> Surface error message details

tests/test_catalog.py, up42/catalog.py, up42/order.py, up42/viztools.py
- Removes sentinel from catalog quicklook viz functionality
- adds capella (preliminary, the sensor schema will be refactored to avoid hardcoding
- Makes bands parameter optional for the image visualizations
- Automatically determines if 1 or 3 bands should be plotted by default
Urgent request for demo, code review after merging.
Items:
For release:
=> Improve quicklooks plotting - bands selection

tests/fixtures.py, tests/test_catalog.py, up42/catalog.py
Splitting up the tasking PR into easier to review logical steps.
This PR splits up the catalog class into CatalogBase and Catalog (The tasking class later will inherit from CatalogBase). No functionality change.
Items:
For release:
=> Split catalog base

tests/test_catalog.py, up42/catalog.py
Some new collections (Capella) require different parameter definitions, this PR adjusts the construct_parameter functions for search and ordering to have more parameters as optional.
Items:
For release:
=> Adjust constructor parameters

tests/test_catalog.py, tests/test_e2e_catalog.py, up42/catalog.py
- Removes hardcoding of sensors supported for quicklooks_download
- Changes parameter sensor to collection (breaking change)
Items:
For release:
=> Quicklooks download generic collection support

setup.py
remove upper version requirement of Python
Items:
For release:
=> remove upper version requirement of Python

docs/macros.py, docs/reference/up42-reference.md, tests/context.py, tests/fixtures/__init__.py, tests/fixtures/fixtures_main.py, tests/test_initialization.py, tests/test_main.py, tests/test_tools.py, up42/__init__.py, up42/initialization.py, up42/main.py, up42/tools.py, up42/utils.py, up42/viztools.py, up42/workflow.py
Restructures package init, moves functions into separate modules (main and initialization). Easier to read & test, and avoids that package unrelated imports are available at `up42` object level, thanks @janchrizz for feedback. 
Also removes the Tools class, which structurally did not make sense, now direct functions in main/viztools/remaining direct functions in tools module.
Items:
For release:
=> Initalization restructure

tests/mock_data/data_products.json, tests/test_catalog.py, up42/catalog.py
Applies the filter for `type` and `isintegrated` in get_data_products also on `basic=False` configuration. Thanks @perusio for the catch!
Items:
For release:
=> Fix data product filter with basic=False

tests/test_workflow.py, up42/workflow.py
- Remove limitation that only assets created from blocks are allowed to be used in workflow (now supported on platform)
- Deprecate parameter assets (asset object), use asset_ids (list of str)
Items:
For release:
=> Remove block limitation for assets in workflows

tests/test_utils.py, up42/catalog.py, up42/tasking.py, up42/utils.py
- Simplifies autocomplete_order_parameters
- Adds log message if no aoi is required for a data product
Items:
For release:
=> Refactor autocomplete order parameters

tests/fixtures/fixtures_globals.py, tests/test_workflow.py, up42/workflow.py
Changes behaviour of `workflow.construct_parameters` to be more user friendly.
- In workflow.construct_parameters, adds any parameters with `None` default, previously only non-None parameters were added.
- If a parameter is required but has no default value, now adds that value as `None` to inform the user about this parameter. Previously parameters without defaults were not added.
- Refactor `_get_default_parameters`
- Adds test cases for the different parameter conditions
- Fixes fixture values which were "None" strings instead of actual strings
Items:
For release:
=> Handle required non default workflow.construct_parameters

up42/catalog.py, up42/tasking.py, up42/utils.py
Removes the overcomplicated handling of geometry edge cases for catalog - full image orders & tasking - point geometry.
Wrong parameters here should be handled on API level. Now allows providing a Point geometry for tasking, but does not validate the order_parameters.
Items:
For release:
=> Simplify geometry handling point

tests/test_initialization.py
fix initialization test - set auth to none
Items:
For release:
=> fix initialization test - set auth to none

tests/context.py, tests/test_utils.py, up42/catalog.py, up42/main.py, up42/tasking.py, up42/utils.py, up42/workflow.py
Replaces internal `utils.format_time_period` with `utils.format_time` for more flexibility to adjust single dates & explicit communication when setting end of day time. Also fixes some Python types for dates.
Required for https://github.com/up42/up42-py/pull/391
Items:
For release:
=> Format time util

tests/fixtures/fixtures_asset.py, tests/fixtures/fixtures_globals.py, tests/fixtures/fixtures_storage.py, tests/test_asset.py, tests/test_storage.py, up42/asset.py, up42/storage.py, up42/utils.py
Updates to the Storage 2.0 API revamp
- Adjusts endpoints for get-assets, asset-info, asset-download-url
- Adds asset-update-metadata
- Adjusts to new asset metadata conventions
Items:
* [] Ran live-tests
For release:
=> Adapt to storage 2.0 API changes

up42/__init__.py
Makes the package version available from the up42 import as module level dunder
Items:
For release:
=> add version to init

docs/reference/up42-reference.md, up42/asset.py, up42/viztools.py
Fixes `up42.read_vector_geometry` and `asset.change_metadata` not showing up in docs reference.
Items:
For release:
=> Docs reference fixes

.circleci/config.yml
Use new ci context to consolodiate publishing of up42 python packages
Items:
For release:
=> New ci context for package publishing

docs/macros.py, docs/reference/asset-reference.md, docs/reference/catalog-reference.md, docs/reference/job-reference.md, docs/reference/jobcollection-reference.md, docs/reference/jobtask-reference.md, docs/reference/order-reference.md, docs/reference/project-reference.md, docs/reference/storage-reference.md, docs/reference/tasking-reference.md, docs/reference/up42-reference.md, docs/reference/webhooks-reference.md, docs/reference/workflow-reference.md, mkdocs.yml, requirements-docs.txt, up42/viztools.py
- Corrects missing visualization options in code reference
- Simplifies mkdocstrings rendering options
- downgrades mkdocs material version due to dependency issue w mkdocs-jupyter
Items:
For release:
=> Docs changes

tests/fixtures/fixtures_globals.py, tests/test_storage.py, up42/storage.py
Adds additional filter parameters to zstorage.get_assets` which were added with API v2.
Items:
For release:
=> Additional get assets filters

tests/fixtures/fixtures_asset.py, tests/test_asset.py, up42/asset.py
Adds the asset stac info call. Equivalent to `asset.info` for up42 platform specific metadata but for the  stac conform metadata of the asset's items.
- TODO: Livetest needs to finally adjusted when all stac items are correctly extracted on prod.
Items:
For release:
=> Asset stac info call

requirements.txt, tests/fixtures/fixtures_globals.py, tests/fixtures/fixtures_storage.py, tests/test_main.py, tests/test_storage.py, up42/storage.py
Draft for integrating pystac client that is authenticated with the UP42 storage access. Automatically reauthenticates the token.
Items:
For release:
=> Integrate pystac client

mkdocs.yml, requirements-docs.txt
Pointing the privacy policy to the main UP42 privacy policy page https://up42.com/legal/privacy
Adding the mkdocstrings-python requirement to avoid the python handler error.
Items:
For release:
=> Updating privacy policy to point to the UP42 link.

.circleci/config.yml, pylintrc, pytest.ini, setup.py, tests/fixtures/fixtures_asset.py, tests/fixtures/fixtures_globals.py, tests/test_asset.py, tests/test_storage.py, tests/test_utils.py, up42/asset.py, up42/stac_client.py, up42/storage.py, up42/utils.py
This PR adds the stac_item property to the assets Class.
For doing this we refactored the pystac_client authenticated against the UP42 account and removed support for Python 3.7.
Items:
For release:
=> STAC Item retrieval

tests/fixtures/fixtures_asset.py, tests/fixtures/fixtures_globals.py, tests/test_asset.py, up42/asset.py
**Description**
This PR modifies the stac_item and stac_info methods from the Asset class to consistenly use pystac_client and format their outputs as pystac.ItemCollection, and pystac.Collection objects.
Items:
For release:
=> At 3031 change stac info

docs/tasking.md, examples/tasking/tasking-example.ipynb
Documentation changes made to tasking.md and tasking-example.ipynb:
Replaced this sentence:
“When the order is completed, download its assets from storage.”
→ 
The following statuses mean you can download assets from storage:
- `BEING_FULFILLED`: some order assets are delivered
- `FULFILLED`: all order assets are delivered
=> DOC-631: Update Tasking SDK tutorial

docs/reference/asset-reference.md, docs/reference/catalogbase-reference.md, docs/reference/tasking-reference.md, docs/reference/up42-reference.md, docs/structure.md, mkdocs.yml
Update the docs:
* Convert `up42-reference.md` to Markdown and review the functions.
Additional notes:
* `map_quicklooks`, `plot_quicklooks`, `plot_coverage`, `map_results`, and `plot_results` were removed from the page, they will be added in [this task](https://up42.atlassian.net/browse/DOC-731) and [this task](https://up42.atlassian.net/browse/DOC-726).
* `create_webhook was`, `get_webhook_events`, and `get_webhooks` were removed from the page, they are already added on [Webhooks](https://sdk.up42.com/reference/webhooks-reference/).
* Initialization functions were removed because they are already mentioned on their respective reference pages.
* The functionality overview table wasn't updated, it will be restructured in [this task](https://up42.atlassian.net/browse/DOC-722). 
* Updated …
=> DOC-732: Convert an SDK reference page to markdown: up42

docs/reference/asset-reference.md, docs/reference/project-reference.md
- Convert an SDK reference page to markdown: `project-reference.md`
- Add missing return formats to `asset-reference.md`
=> DOC-728: Convert an SDK reference page to markdown: Project

docs/reference/asset-reference.md, docs/reference/job-reference.md, docs/visualizations.md
- `job-reference.md`: converted the reference page to markdown.
- `asset-reference.md`: fixed type spelling (and requirement for `unpacking`).
- Removed the **Job quicklooks** section from `visualizations.md` because it's not possible to visualize job quicklooks (map or plot).
=> DOC-726: Convert a reference page to markdown: Job

docs/reference/asset-reference.md, examples/asset/asset-example.ipynb
- In `asset-reference.md`, fix example and description.
- In `asset-example.ipynb`, fix cell counts and example.
=> DOC-797: Fix download_stac_asset code snippet example

docs/reference/order-reference.md, docs/reference/up42-reference.md, docs/structure.md
* `order-reference.md`: converted the page to MD.
* `up42-reference.md`: added the description.
* `structure.md`: updated the entries of the converted pages.
=> DOC-729: Convert an SDK reference page to markdown: Order

.circleci/config.yml
Updates Sonarcloud version as the old orb won't be supported from 15th of November. 
See https://up-42.slack.com/archives/C04FLMD3YK0/p1699376601021069
Items:
For release:
=> Update Sonarcloud Orb Version

.circleci/config.yml
Adding a step to run whole SDK E2E tests for all categories after deploy step in the pipeline. This won't block release, but immediate notification is given if any failures.
Items:
* [ N/A] Ran test & live-tests
* [ N/A] Implemented (new) unit tests
* [ N/A] Removed credentials
* [N/A ] Removed argument pointing to staging
* [ N/A] Updated [documentation](sdk.up42.com)
=> AT-4127 Run SDK E2E tests in Release Pipeline

.circleci/config.yml
Scope: Use cimg/python3.11 as base docker image for publishing to pypi.
Items:
For release:
=> update docker image for publishing

docs/reference/asset-reference.md, docs/reference/catalog-reference.md, docs/reference/catalogbase-reference.md, docs/reference/job-reference.md, docs/reference/jobcollection-reference.md, docs/reference/jobtask-reference.md, docs/reference/order-reference.md, docs/reference/project-reference.md, docs/reference/storage-reference.md, docs/reference/tasking-reference.md, docs/reference/up42-reference.md, docs/reference/webhook-reference.md, docs/reference/workflow-reference.md
Corresponds to Documentation Jira tasks:
- [DOC-831](https://up42.atlassian.net/browse/DOC-831)
- [DOC-812](https://up42.atlassian.net/browse/DOC-812)
- Removed initialization code blocks on reference pages
- Changed “The returned format is `this`.” → “The returned data type is `this.`” on all reference pages
[DOC-831]: https://up42.atlassian.net/browse/DOC-831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOC-812]: https://up42.atlassian.net/browse/DOC-812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOC-831 + DOC-812: Update reference articles

docs/authentication.md, docs/notebooks/catalog-example.ipynb, docs/notebooks/order-assets-example.ipynb, docs/notebooks/stac-example.ipynb, docs/notebooks/storage-assets-example.ipynb, docs/notebooks/tasking-example.ipynb
[DOC-925](https://up42.atlassian.net/browse/DOC-925?atlOrigin=eyJpIjoiYTE5MWRlMGE2NjdjNGM5MDkwYzMyZDBhNDM5NTNmMDgiLCJwIjoiaiJ9): Update the auth cell in Notebooks
- `/notebooks`
- Remove the example in 5 notebooks to provide credentials directly in code
- Provide only the example with a file
- `authentication.md`
- Changed name of file from `config.json` -> `credentials.json` to match other notebooks.
[DOC-925]: https://up42.atlassian.net/browse/DOC-925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOC-925: Update auth in notebooks

tests/conftest.py, tests/fixtures/fixtures_order.py, tests/test_catalog.py, tests/test_order.py, up42/order.py
Fixing the OrderV2 migration to allow tasking orders.
Items:
For release:
=> AT-4219 Fixing tasking order translate bug

up42/order.py
=> AT4219 bugfix display name tasking orders

CHANGELOG.md, pyproject.toml, tests/http/test_oauth.py, up42/http/config.py, up42/http/oauth.py, up42/http/session.py
Generalize new auth stack to include account authentication in addition to project authentication
Items:
For release:
=> AT-4866 Account token retrieval

CHANGELOG.md, pyproject.toml, tests/fixtures/fixtures_tasking.py, tests/test_auth.py, up42/auth.py, up42/catalog.py
Injection of functional dependencies and test coverage for auth.py
Items:
For release:
=> [AT-4915] Dependency injection and test coverage for auth.py

CHANGELOG.md, docs/theme_override_home/main.html, pyproject.toml
- Removed upper bound for Python 3.12.
- Dropped support for Python 3.8.
- New authentication token are retrieved upon expiration instead of every request.
- Dropped tenacity, requests-oauthlib and types-oauthlib as dependencies.
- Updated the deprecation date for `Jobs`, `Workflow`, and `Projects` related features.
- Multiple refactoring improvements.
Items:
For release:
=> Release version 0.37.1

CHANGELOG.md, pyproject.toml, tests/fixtures/fixtures_auth.py, tests/fixtures/fixtures_globals.py, tests/test_main.py, up42/__init__.py, up42/main.py
Dropped `get_blocks`, `get_block_details` and `get_block_coverage` from `main.py`
Items:
For release:
=> [PT-5138] Drop get blocks, get block details and block coverage

.circleci/config.yml
Updating the run command for `sdk-tests`, so tests run with 10 workers in parallel, only merge after this https://github.com/up42/sdk-tests/pull/51 is merged!
=> PT-5266 Run sdk-tests in parallel

CHANGELOG.md, pyproject.toml, tests/test_base.py, tests/test_initialization.py, up42/__init__.py, up42/base.py, up42/initialization.py
Moving webhooks related code from `base.py` to avoid circular references
Items:
For release:
=> [PT-5013] Move webhooks out of base

CHANGELOG.md, docs/macros.py, pyproject.toml, tests/test_initialization.py, tests/test_webhooks.py, up42/initialization.py, up42/webhooks.py
Drops Webhooks class and moves its legacy instance methods as class methods to Webhook class
Items:
For release:
=> [PT-5013] Drop Webhooks class

CHANGELOG.md, pyproject.toml, up42/catalog.py, up42/initialization.py, up42/utils.py, up42/webhooks.py
Deprecate the following functions:
1. initialization::create_webhook
2. initialization::initialize_webhook
3. initialization::get_webhooks
4. initialization::get_webhook_events
5. Webhook::id
6. Webhook::info
7. Webhook::create
8. Webhook::update
9. return_json in Webhook::all
Items:
For release:
=> [PT-5318] Deprecate legacy webhooks methods

CHANGELOG.md, pyproject.toml, tests/test_processing.py, up42/processing.py
Job registry returns page links as relative paths
Items:
For release:
=> [Bugix] Convert relative job links to absolute links

CHANGELOG.md, pyproject.toml, tests/test_processing.py, up42/processing.py
Job execution endpoint requires workspaceId as query parameter.
Items:
For release:
=> [Bugfix] Missing workspace id in job execution request

CHANGELOG.md, pyproject.toml, tests/test_catalog.py, tests/test_glossary.py, up42/__init__.py, up42/catalog.py, up42/glossary.py, up42/tasking.py
=> [PT-5547] Moved ProductGlossary to glossary.py

CHANGELOG.md, pyproject.toml, tests/test_tasking.py, up42/asset.py, up42/tasking.py
=> [TechDebt] Fix test coverage Tasking::construct_order_parameters

CHANGELOG.md, pyproject.toml, tests/test_tasking.py, up42/tasking.py
The endpoint `/v2/tasking/feasibility` is deprecated and should be replaced with `/v2/tasking/feasibility-studies`.
Refer to the [UP42 API reference](https://developer.up42.com/reference/listtaskingfeasibilitystudies)
Checklist:
=> Change feasibility endpoint url

.circleci/config.yml
Based on https://up42.atlassian.net/browse/PT-6472
Since the SDK is now owned by all teams, we need to move away from notifying Processing channel on failures and instead ping a generic channel: `e2e-sdk-test-alerts` where every other team can see.
Checklist:
=> PT-6472 Redirect E2E failures to e2e-sdk-test-alerts channel

.github/CODEOWNERS
Explicitly allowing different teams to push changes into `/up42/__init__.py` without needing an approval from `@up42/sdk-team`.
=> Update codeowners of __init__
